<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>
<link rel="stylesheet" href="/home/cedcoss/git /events_phalcon/src/app/views/index/style.css">
		
		<title>Compass Starter by Ariona, Rian</title>

		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Roboto:300,400,700|" rel="stylesheet" type="text/css">
		<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">

		<!-- Loading main css file -->
		<link rel="stylesheet" href="style.css">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>


	<body>



<table class="table m-5 bg-info">
        <thead>
            <tr>
            <!-- <th scope="col">#</th> -->
            <th scope="col">Key</th>
            <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
<?php
//  echo count($air['alerts']['alert'][0]);
//  die;
if(count($air['alerts']['alert'][0])>0){
    // echo "<pre>";
    // print_r($air['alerts']['alert'][0]);
   foreach($air['alerts']['alert'][0] as $key =>$value){
    //    echo $key , $value ,"<br>";
       ?>

    <tr>
        <td><?php echo $key; ?></td>
        <td><?php echo $value; ?></td>
   </tr>
<?php
} }else{?>
<td><?php echo "No Alert" ?></td>
            
<?php 
} ?>
</tbody>
</table>
		
<script src="js/jquery-1.11.1.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/app.js"></script>
		
	</body>

</html>