<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>
<link rel="stylesheet" href="/home/cedcoss/git /events_phalcon/src/app/views/index/style.css">
		
		<title>Compass Starter by Ariona, Rian</title>

		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Roboto:300,400,700|" rel="stylesheet" type="text/css">
		<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">

		<!-- Loading main css file -->
		<link rel="stylesheet" href="style.css">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>


	<body>
		
    <section class="vh-100" style="background-color: #4B515D;">
   <?php  
//    foreach($Astronomy as $key=>$value){
    //    echo "<pre>";
    //    print_r($value);
    //     // print_r($key);
    //    die;
  ?> 
  <?php ?>
  <div class="container py-5 h-100">

    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-8 col-lg-6 col-xl-4">

        <div class="card" style="color: #4B515D; border-radius: 35px;">
          <div class="card-body p-4">

            <div class="d-flex">
              <h6 class="flex-grow-1">Astronomy of <?php echo $Astronomy['location']['name'] ?></h6>
              <h6><?php echo $Astronomy['location']['localtime'] ?></h6>
            </div>

            <div class="d-flex flex-column text-center mt-5 mb-4">
            moon_phase<h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"> <?php echo $Astronomy['astronomy']['astro']['moon_phase'] ?>  </h6>
            </div>

            <div class="d-flex align-items-center">
              <div class="flex-grow-1" style="font-size: 1rem;">
                <div><i class="fas fa-tint fa-fw" style="color: #868B94;"></i> moon_illumination <span class="ms-1"><?php echo $Astronomy['astronomy']['astro']['moon_illumination'] ?>  </span></div>
                <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"> Sunrises : <?php echo $Astronomy['astronomy']['astro']['sunrise'] ?>  </span></div>
                <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"> Sunset : <?php echo $Astronomy['astronomy']['astro']['sunset'] ?>  </span></div>
              </div>
              <div>
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-weather/ilu1.webp" width="100px">
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
<?php  ?>
  </div>
</section>
		
		<script src="js/jquery-1.11.1.min.js"></script>
		<script src="js/plugins.js"></script>
		<script src="js/app.js"></script>
		
	</body>

</html>


<!-- Array
(
    [location] => Array
        (
            [name] => Lucknow City
            [region] => Uttar Pradesh
            [country] => India
            [lat] => 26.85
            [lon] => 80.92
            [tz_id] => Asia/Kolkata
            [localtime_epoch] => 1649249377
            [localtime] => 2022-04-06 18:19
        )

    [astronomy] => Array
        (
            [astro] => Array
                (
                    [sunrise] => 05:50 AM
                    [sunset] => 06:27 PM
                    [moonrise] => 10:31 AM
                    [moonset] => 12:07 AM
                    [moon_phase] => Waxing Crescent
                    [moon_illumination] => 46
                )

        )

) -->