<?php
    // echo "<pre>";
    // print_r($item_playlist);
?>
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>


    <table class="table bg-danger">
        <thead>
            <tr>
            <th scope="col">no</th>
            <th scope="col">Name</th>
            <th scope="col">Duration</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        $v = 0;
        foreach($item_playlist['items'] as $key=>$value){ $v = $v + 1;?>
            
            <tr>
            <th scope="row"><?php echo $v ?></th>
            <td><?php echo $value['track']['name']; ?></td>
            <td><?php echo $value['track']['duration_ms']; ?>  ms</td>
            <td>
                <form method="POST" action="/index/removeitem">
                    <input type="hidden" name="uri" value="<?php echo $value['track']['uri'] ?>">
                    <button class="btn btn-outline-success my-2 my-sm-0 col-sm m-5" name="delete" type="submit">Remove</button>
                </form>
            </td>
            
            </tr>
        <?php } ?>
    </table>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

<!-- <form method="POST" action="/index/goplaylist">
                    <input type="hidden" name="uri" value="<?php echo $value['id']; ?>">
                    <button class="btn btn-outline-success my-2 my-sm-0 col-sm m-5" name="delete" type="submit">go</button>
                </form> -->