<?php
 echo "<pre>";
//  echo $type;
//  die;
//  print_r( $data["$type"]['items']);
    // echo $key," ",$value, "<br>";
    // print_r($value);
// }
 
//  die;
?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>
<link rel="stylesheet" href="/home/cedcoss/git /events_phalcon/src/app/views/index/style.css">
		
		<title>Compass Starter by Ariona, Rian</title>

		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Roboto:300,400,700|" rel="stylesheet" type="text/css">
		<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">

		<!-- Loading main css file -->
		<link rel="stylesheet" href="style.css">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>
	<body>
    <form method="POST" action="/index/playlist">
        <input type="hidden" name="token_id" value="<?php echo $token ?>">
        <button class="btn btn-outline-success my-2 my-sm-0 col-sm m-5" name="playlist" type="submit">Create PlayList</button>
    </form>
    <a class="btn btn-outline-success my-2 my-sm-0 col-sm m-5" href="/index/getplaylist">PlayList</a>
        <!-- <div class="container-fluid"> -->
        <?php  
                foreach($data["$type"]['items'] as $key => $value){
        
        ?>
                <div class="card">
                    <div class="row">
                        <div class="col-4">
                            <img src="<?php echo $value['images'][0]['url'] ?>" style="height:400px;width:210px;" alt="" srcset="">
                        </div>
                        <div class="col-8">
                            <blockquote class="blockquote">
                            <p>Owner: <?php echo $value['name'] ?> </p>
                            <p> Listen : <a href="<?php echo $value['owner']['external_urls']['spotify'] ?>"> Listen </a> </p>
                            <p>Start :  </p>
                            <p>match :</p> <?php echo $value['type']; ?>
                            <!-- <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer> -->
                            </blockquote>
                            <?php if($value['type']=="track"){ ?>
                            <form method ="POST" action="/index/addsong">
                                <input type="hidden" name="uri" value="<?php echo $value['uri']; ?>">
                                <button class="btn btn-outline-success my-2 my-sm-0 col-sm m-5" name="add" type="submit">Add to play List</button>
                            </form>  
                        <?php } ?>
                        </div>
                    </div>
                
                </div>
        <?php } ?>








    <script src="js/jquery-1.11.1.min.js"></script>
		<script src="js/plugins.js"></script>
		<script src="js/app.js"></script>
		
	</body>

</html>

