<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">
        <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>
<link rel="stylesheet" href="/home/cedcoss/git /events_phalcon/src/app/views/index/style.css">
		
		<title>Compass Starter by Ariona, Rian</title>

		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Roboto:300,400,700|" rel="stylesheet" type="text/css">
		<link href="fonts/font-awesome.min.css" rel="stylesheet" type="text/css">

		<!-- Loading main css file -->
		<link rel="stylesheet" href="style.css">
		
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->

	</head>
<?php 
// echo $sport['golf'][0]['country']
?>

	<body>
        <div class="container m-5">
        <div class="card">
            <div class="card-header">
                <?php echo $sport['golf'][0]['stadium'] ?> &nbsp; Stadium
            </div>
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                <p>country:  <?php echo $sport['golf'][0]['country']?></p>
                <p>Tournament  :  <?php echo $sport['golf'][0]['tournament'] ?></p>
                <p>Start :  <?php echo $sport['golf'][0]['start'] ?></p>
                <p>match :  <?php echo $sport['golf'][0]['match'] ?></p>
                <!-- <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer> -->
                </blockquote>
            </div>
        </div>

        </div>







    <script src="js/jquery-1.11.1.min.js"></script>
		<script src="js/plugins.js"></script>
		<script src="js/app.js"></script>
		
	</body>

</html>





<!-- 
 [0] => Array
                (
                    [stadium] => Burnley
                    [country] => United Kingdom
                    [region] => 
                    [tournament] => Premier League
                    [start] => 2022-04-06 19:30
                    [match] => Burnley vs Everton
                )


) -->